version: '3.6'

services:
  filament:
    build: ./docker/php
    container_name: filament
    image: filament
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: filament
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mm-network

  nginx:
    build: ./docker/nginx
    container_name: nginx
    image: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./app:/var/www
    networks:
      - mm-network

  db:
    build: ./docker/mysql
    container_name: db
    image: db
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - dbdata_mysql:/var/lib/mysql
    networks:
      - mm-network

# docker networks
networks:
  mm-network:
    driver: bridge

# volumes
volumes:
  dbdata_mysql:
    driver: local
